# Generated by Django 5.1 on 2024-09-06 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('reference', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=15)),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
                ('select_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.membership_plan')),
                ('select_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.trainer')),
            ],
        ),
    ]
