# Generated by Django 5.1 on 2024-09-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_membership_plan_trainer_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='price',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
