# Generated by Django 5.1 on 2024-09-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_enrollment_due_date_enrollment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
