# Generated by Django 5.1 on 2024-09-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_enrollment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_of_joining',
            field=models.DateField(auto_now_add=True),
        ),
    ]
